### PR TITLE
Feature/natverse updates

### PR DESCRIPTION
**Pull request by SridharJagannathan**
For fixing issues #3,#9

### CODE REVIEW

**Comment by SridharJagannathan** [comment]
@jefferis I have checked this functionality and it seems working except 
1) For some reason it skips the main `natverse` module and 'says Skipping 1 packages not available: natverse' seems to be an issue arising from `remotes::update_packages('natverse')`
2) The packages `fishatlas`, `insectbrainr`, seems to have a lower version of `R` as requirement and hence they error out in the function `remotes::update_packages('fishatlas','insectbrainr')`

**Comment by SridharJagannathan** [comment]
> 1. For some reason it skips the main `natverse` module and 'says Skipping 1 packages not available: natverse' seems to be an issue arising from `remotes::update_packages('natverse')`

This issue seems to arise as I had a local version installed for debugging, once I install from github the specific branch seems to be resolved.

**Comment by jefferis** [comment]
Can you clarify re fishatlas version requirement?

**Comment by jefferis** [comment]
Re fishatlas the R version requirement is >=2.10. That means that it will be satisfied by any recent version of R in the 3.x series and therefore should not cause any install trouble. What is the error message in install?

**Comment by SridharJagannathan** [comment]
@jefferis The basic functionality is working along with updates, I have fixed the warning for `:::` as well. We can remove the custom functionality once we get the `remotes` package to fix the error for second level dependencies on the `github` packages. Can you please merge this now, I will later add the issue number of the remotes to `natverse` to a new issue (which will be fixed when `remotes` releases a new version).

**Comment by jefferis** [comment]
We could also highlight the direct dependencies when they are out of date (i.e. of natverse)

Also make sure that all of http://natverse.org/packages/ are listed as Imports.

**Comment by jefferis** [comment]
Problem installing new GitHub packages
```
 natverse_update(update = T)

The following natverse dependencies are missing!

  fishatlas, insectbrainr
```
```
Browse[2]> missing_df
        package source reponame status
8     fishatlas GitHub     NULL     -2
11 insectbrainr GitHub     NULL     -2
```
```
Checking for remote updates for 21 packages ...
 Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`NULL`) and repo name (`fishatlas`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo. 
```

**Comment by jefferis** [comment]
tinytex appears as extra dependency (prob because it is 3rd order?)

```

The following natverse dependencies are out-of-date, see details below:

We recommend updating them by running:
natverse_update(update=TRUE)

package              remote         local          source   status            
-------------------  -------------  -------------  -------  ------------      
abind                1.4-5          1.4-5          CRAN     ✔ 
alphashape3d         1.3            1.3            CRAN     ✔ 
assertthat           0.2.1          0.2.1          CRAN     ✔ 
backports            1.1.5          1.1.4          CRAN     ✖ 
base64enc            0.1-3          0.1-3          CRAN     ✔ 
BH                   1.69.0-1       1.69.0-1       CRAN     ✔ 
callr                3.3.2          3.3.2          CRAN     ✔ 
catmaid              dd9c91909...   e06ee89c7...   GitHub   ✖ 
catnat               9232efbbc...   075113b83...   GitHub   ✖ 
cli                  1.1.0          1.1.0          CRAN     ✔ 
colorRamps           2.3            2.3            CRAN     ✔ 
colorspace           1.4-1          1.4-1          CRAN     ✔ 
commonmark           1.7            1.7            CRAN     ✔ 
covr                 3.3.2          3.3.0          CRAN     ✖ 
crayon               1.3.4          1.3.4          CRAN     ✔ 
crosstalk            1.0.0          1.0.0          CRAN     ✔ 
curl                 4.2            4.0            CRAN     ✖ 
DependenciesGraphs   3c33e2a1c...   3c33e2a1c...   GitHub   ✔ 
digest               0.6.22         0.6.21         CRAN     ✖ 
doParallel           1.0.15         1.0.15         CRAN     ✔ 
dplyr                0.8.3          0.8.3          CRAN     ✔ 
drvid                cdd2a48c7...   cdd2a48c7...   GitHub   ✔ 
ellipsis             0.3.0          0.3.0          CRAN     ✔ 
elmr                 fadfe1c86...   e6da79673...   GitHub   ✖ 
evaluate             0.14           0.14           CRAN     ✔ 
fafbseg              479dd1340...   0.6.5.9000     GitHub   ✖ 
fansi                0.4.0          0.4.0          CRAN     ✔ 
fastmap              1.0.1          1.0.1          CRAN     ✔ 
filehash             2.4-2          2.4-2          CRAN     ✔ 
fishatlas            b7e85e4e1...   b7e85e4e1...   GitHub   ✔ 
flycircuit           cc4594f47...   cc4594f47...   GitHub   ✔ 
foreach              1.4.7          1.4.7          CRAN     ✔ 
geometry             0.4.4          0.4.4          CRAN     ✔ 
ggplot2              3.2.1          3.2.1          CRAN     ✔ 
glue                 1.3.1          1.3.1          CRAN     ✔ 
gtable               0.3.0          0.3.0          CRAN     ✔ 
here                 0.1            0.1            CRAN     ✔ 
highr                0.8            0.8            CRAN     ✔ 
htmltools            0.4.0          0.3.6          CRAN     ✖ 
htmlwidgets          1.5.1          1.3            CRAN     ✖ 
httpuv               1.5.2          1.5.2          CRAN     ✔ 
httr                 1.4.1          1.4.1          CRAN     ✔ 
hunspell             3.0            3.0            CRAN     ✔ 
igraph               1.2.4.1        1.2.4.1        CRAN     ✔ 
insectbrainr         e80f497aa...   e80f497aa...   GitHub   ✔ 
iterators            1.0.12         1.0.12         CRAN     ✔ 
jsonlite             1.6            1.6            CRAN     ✔ 
knitr                1.25           1.25           CRAN     ✔ 
labeling             0.3            0.3            CRAN     ✔ 
later                1.0.0          0.8.0          CRAN     ✖ 
lazyeval             0.2.2          0.2.2          CRAN     ✔ 
linprog              0.9-2          0.9-2          CRAN     ✔ 
lpSolve              5.6.13.3       5.6.13.3       CRAN     ✔ 
magic                1.5-9          1.5-9          CRAN     ✔ 
magrittr             1.5            1.5            CRAN     ✔ 
manipulateWidget     0.10.0         0.10.0         CRAN     ✔ 
markdown             1.1            1.1            CRAN     ✔ 
mime                 0.7            0.7            CRAN     ✔ 
miniUI               0.1.1.1        0.1.1.1        CRAN     ✔ 
Morpho               2.7            2.7            CRAN     ✔ 
munsell              0.5.0          0.5.0          CRAN     ✔ 
mvbutils             2.8.232        2.8.232        CRAN     ✔ 
nabor                0.5.0          0.5.0          CRAN     ✔ 
nat                  30ea6d540...   1.9.2          GitHub   ✖ 
nat.flybrains        5d2542b3d...   5d2542b3d...   GitHub   ✔ 
nat.nblast           1.6.2          1.6.2          CRAN     ✔ 
nat.templatebrains   41f63805b...   41f63805b...   GitHub   ✔ 
nat.utils            0.5.1          0.5.1          CRAN     ✔ 
neuprintr            fb25dcb9c...   ec18f2124...   GitHub   ✖ 
pbapply              1.4-2          1.4-2          CRAN     ✔ 
pillar               1.4.2          1.4.2          CRAN     ✔ 
pkgconfig            2.0.3          2.0.3          CRAN     ✔ 
plogr                0.2.0          0.2.0          CRAN     ✔ 
plyr                 1.8.4          1.8.4          CRAN     ✔ 
png                  0.1-7          0.1-7          CRAN     ✔ 
praise               1.0.0          1.0.0          CRAN     ✔ 
processx             3.4.1          3.4.1          CRAN     ✔ 
promises             1.1.0          1.0.1          CRAN     ✖ 
ps                   1.3.0          1.3.0          CRAN     ✔ 
purrr                0.3.3          0.3.2          CRAN     ✖ 
R6                   2.4.0          2.4.0          CRAN     ✔ 
RColorBrewer         1.1-2          1.1-2          CRAN     ✔ 
Rcpp                 1.0.2          1.0.2          CRAN     ✔ 
RcppArmadillo        0.9.800.1.0    0.9.700.2.0    CRAN     ✖ 
RcppEigen            0.3.3.5.0      0.3.3.5.0      CRAN     ✔ 
RcppProgress         0.4.1          0.4.1          CRAN     ✔ 
readobj              0.3.2          0.3.2          CRAN     ✔ 
remotes              2.1.0          2.1.0          CRAN     ✔ 
reshape2             1.4.3          1.4.3          CRAN     ✔ 
rgl                  0.100.30       0.100.30       CRAN     ✔ 
rlang                0.4.0          0.4.0          CRAN     ✔ 
rlist                0.4.6.1        0.4.6.1        CRAN     ✔ 
rmarkdown            1.16           1.15           CRAN     ✖ 
rprojroot            1.3-2          1.3-2          CRAN     ✔ 
Rvcg                 0.18           0.18           CRAN     ✔ 
scales               1.0.0          1.0.0          CRAN     ✔ 
sessioninfo          1.1.1          1.1.1          CRAN     ✔ 
shiny                1.4.0          1.3.2          CRAN     ✖ 
shinydashboard       0.7.1          0.7.1          CRAN     ✔ 
sourcetools          0.1.7          0.1.7          CRAN     ✔ 
spelling             2.1            2.1            CRAN     ✔ 
stringi              1.4.3          1.4.3          CRAN     ✔ 
stringr              1.4.0          1.4.0          CRAN     ✔ 
testthat             2.2.1          2.2.1          CRAN     ✔ 
tibble               2.1.3          2.1.3          CRAN     ✔ 
tidyselect           0.2.5          0.2.5          CRAN     ✔ 
utf8                 1.1.4          1.1.4          CRAN     ✔ 
vctrs                0.2.0          0.2.0          CRAN     ✔ 
viridisLite          0.3.0          0.3.0          CRAN     ✔ 
visNetwork           2.0.8          2.0.7          CRAN     ✖ 
webshot              0.5.1          0.5.1          CRAN     ✔ 
withr                2.1.2          2.1.2          CRAN     ✔ 
xfun                 0.10           0.9            CRAN     ✖ 
XML                  3.98-1.20      3.98-1.20      CRAN     ✔ 
xml2                 1.2.2          1.2.2          CRAN     ✔ 
xtable               1.8-4          1.8-4          CRAN     ✔ 
yaml                 2.2.0          2.2.0          CRAN     ✔ 
zeallot              0.1.0          0.1.0          CRAN     ✔ 

Checking for remote updates for 20 packages ...
These packages have more recent versions available.
Which would you like to update?

 1: All                                                 
 2: CRAN packages only                                  
 3: None                                                
 4: backports    (1.1.4        -> 1.1.5       ) [CRAN]  
 5: catmaid      (e06ee89c7... -> dd9c91909...) [GitHub]
 6: catnat       (075113b83... -> 9232efbbc...) [GitHub]
 7: covr         (3.3.0        -> 3.3.2       ) [CRAN]  
 8: curl         (4.0          -> 4.2         ) [CRAN]  
 9: digest       (0.6.21       -> 0.6.22      ) [CRAN]  
10: elmr         (e6da79673... -> fadfe1c86...) [GitHub]
11: htmltools    (0.3.6        -> 0.4.0       ) [CRAN]  
12: htmlwidgets  (1.3          -> 1.5.1       ) [CRAN]  
13: later        (0.8.0        -> 1.0.0       ) [CRAN]  
14: neuprintr    (ec18f2124... -> fb25dcb9c...) [GitHub]
15: promises     (1.0.1        -> 1.1.0       ) [CRAN]  
16: purrr        (0.3.2        -> 0.3.3       ) [CRAN]  
17: RcppArmad... (0.9.700.2.0  -> 0.9.800.1.0 ) [CRAN]  
18: rmarkdown    (1.15         -> 1.16        ) [CRAN]  
19: shiny        (1.3.2        -> 1.4.0       ) [CRAN]  
20: visNetwork   (2.0.7        -> 2.0.8       ) [CRAN]  
21: xfun         (0.9          -> 0.10        ) [CRAN]  
22: tinytex      (0.15         -> 0.16        ) [CRAN]  

Enter one or more numbers, or an empty line to skip updates:
```

**Comment by jefferis** [comment]
Telling you about locally installed GitHub packages when preparing to install CRAN updates

```
Enter one or more numbers, or an empty line to skip updates:
1
backports    (1.1.4        -> 1.1.5       ) [CRAN]
catmaid      (e06ee89c7... -> dd9c91909...) [GitHub]
catnat       (075113b83... -> 9232efbbc...) [GitHub]
covr         (3.3.0        -> 3.3.2       ) [CRAN]
curl         (4.0          -> 4.2         ) [CRAN]
digest       (0.6.21       -> 0.6.22      ) [CRAN]
elmr         (e6da79673... -> fadfe1c86...) [GitHub]
htmltools    (0.3.6        -> 0.4.0       ) [CRAN]
htmlwidgets  (1.3          -> 1.5.1       ) [CRAN]
later        (0.8.0        -> 1.0.0       ) [CRAN]
neuprintr    (ec18f2124... -> fb25dcb9c...) [GitHub]
promises     (1.0.1        -> 1.1.0       ) [CRAN]
purrr        (0.3.2        -> 0.3.3       ) [CRAN]
RcppArmad... (0.9.700.2.0  -> 0.9.800.1.0 ) [CRAN]
rmarkdown    (1.15         -> 1.16        ) [CRAN]
shiny        (1.3.2        -> 1.4.0       ) [CRAN]
visNetwork   (2.0.7        -> 2.0.8       ) [CRAN]
xfun         (0.9          -> 0.10        ) [CRAN]
tinytex      (0.15         -> 0.16        ) [CRAN]
Skipping 1 packages not available: fafbseg
Skipping 1 packages ahead of CRAN: nat
Installing 15 packages: backports, covr, curl, digest, htmltools, htmlwidgets, later, promises, purrr, RcppArmadillo, rmarkdown, shiny, visNetwork, xfun, tinytex
```

**Comment by jefferis** [comment]
Easiest thing will just be to ignore any locally installed packages, informing the user that they will not be updated!

**Pull request merged**
