### PR TITLE
PR to remove all internal functions that are used from remotes

### PR DESCRIPTION
**Pull request by SridharJagannathan**
The internal functions used in `remotes` has been renamed. This has resulted in #19 
Check the actual PR in `remotes` that led to this: https://github.com/r-lib/remotes/pull/483/files
The goal of this PR would be to remove all internal functions from `remotes` and use them with in-house adaptations.
This is an ongoing PR and would be updated.

### CODE REVIEW

**Comment by jefferis** [comment]
Oh I'm sorry @SridharJagannathan, this looked complicated in the end. What's the summary? It looks like you ended up bringing in some internal code from remotes. Will it work with older versions of remotes as well or does it need some particular version?

**Comment by SridharJagannathan** [comment]
@jefferis No worries, so far good, I brought in some code and adapted, so far the functionality is untouched, only one more function to go, I will then make a self code review after that and add more test case to check the robustness of the functionality. This should look in good shape by the end of the day.

**Comment by SridharJagannathan** [comment]
All the changes were limited to the function `natverse_deps()`
The following where the checks performed to make sure the functionality has not changed:
- [x] Self code-review of all changes
- [x] Use different versions of `natverse` and perform the following check:
       1) Install `remotes` older version like `remotes::install_github("r-lib/remotes@v2.1.1")`
       2) Install `natverse` version prior to the PR merge using 
           `devtools::install_github('natverse/natverse', force = TRUE)`
           (Don't install any other package in this run) 
       3) Run `old_df <- natverse::natverse_deps()`
       4) Install `remotes` latest version like `remotes::install_github("r-lib/remotes")`
       5) Install `natverse` current version using `R-Studio` like `Build->Install and Restart`
       6) Run `new_df <- natverse::natverse_deps()`
       7) Run this `all.equal(old_df, new_df)` should return `TRUE`

**Review by jefferis — COMMENTED** [review]
Hi @SridharJagannathan thanks a lot for your work on this. The only thing that worries me is the dependency on the latest version of remotes. Can you think of any unintended consequences? I wonder about rebuilding the docker image as a test.

**Comment by jefferis** [comment]
> Hi @SridharJagannathan thanks a lot for your work on this. The only thing that worries me is the dependency on the latest version of remotes. Can you think of any unintended consequences? I wonder about rebuilding the docker image as a test.

I'm going to go ahead and merge since I can see that you have done a very thorough job of testing. I still have some misgivings about remotes >= 2.2.0 but as far as I can see this does not in and of itself require an R version >=3.5.0 (this could happen if a dependency of remotes doesn't work on earlier R). Also it seems that e.g. remotes 2.2.0 is available for people on earlier versions of macosx. Thanks again!

**Pull request merged**
